EDLaboratorio3/Models/Partido.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EDLaboratorio3.Models
{
    public class Partido
    {
        public int NoPartido { get; set; }
        public DateTime FechaPartido { get; set; }
        public string Grupo { get; set; }
        public string Pais1 { get; set; }
        public string Pais2 { get; set; }
        public string Estadio { get; set; }
    }
}

EDLaboratorio3/Controllers/PartidoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EDLaboratorio3.DBContext;
using LibreriaDeClases;
using EDLaboratorio3.Models;
using System.IO;

namespace EDLaboratorio3.Controllers
{
    public class PartidoController : Controller
    {
        // GET: Partido
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult IndexFecha()
        {
            logWriter("VISITO INICIO DE FECHA", HomeController.ruta, true);
            

            return View(DBContext.DefaultConnection.miAVLFechas.EnOrden());
        }
        public ActionResult IndexNoPartido()
        {
            logWriter("VISITO INICIO DE NUMERO DE PARTIDO", HomeController.ruta, true);

            return View(DBContext.DefaultConnection.miAVLNoPartidos.EnOrden());
        }
        
        // GET: Partido/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Partido/CreateFecha
        public ActionResult CreateFecha()
        {  
            return View();
        }        

        // POST: Partido/CreateFecha
        [HttpPost]
        public ActionResult CreateFecha(Partido partido)
        {
            try
            {
                logWriter("VISITO CREAR", HomeController.ruta, true);
                Nodo<Partido> nuevo = new Nodo<Partido>(partido,ArchivoController.CompararFechas);
                DefaultConnection.miAVLFechas.Insertar(nuevo);
                string log = "SE INSERTÓ UN PARTIDO CON FECHA: " + nuevo.dato.FechaPartido.Day.ToString() + "/" + nuevo.dato.FechaPartido.Month.ToString() + "/" + nuevo.dato.FechaPartido.Year.ToString();
                logWriter(log, HomeController.ruta, true);
                DefaultConnection.miAVLFechas.logWriterAsignacion(HomeController.ruta, true);
                return RedirectToAction("IndexFecha");
            }
            catch
            {
                return View("IndexFecha");
            }
        }

        // GET: Partido/CreateNoPartido
        public ActionResult CreateNoPartido()
        {
            return View();
        }

        // POST: Partido/CreateNoPartido
        [HttpPost]
        public ActionResult CreateNoPartido(Partido partido)
        {
            try
            {
                logWriter("VISITO CREAR", HomeController.ruta, true);
                DefaultConnection.miAVLNoPartidos.logWriterAsignacion(HomeController.ruta, true);
                Nodo<Partido> nuevo = new Nodo<Partido>(partido, ArchivoController.CompararNoPartido);
                string log = "SE INSERTÓ UN PARTIDO CON FECHA: " + nuevo.dato.NoPartido.ToString();
                logWriter(log, HomeController.ruta, true);
                DefaultConnection.miAVLNoPartidos.Insertar(nuevo);

                return RedirectToAction("IndexNoPartido");
            }
            catch
            {
                return View("IndexNoPartido");
            }
        }

        // GET: Partido/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Partido/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Partido/Delete/5
        public ActionResult DeleteNoPartido(int id)
        {
            logWriter("VISITO ELIMINAR", HomeController.ruta, true);

            return View(DefaultConnection.miAVLNoPartidos.EnOrden().Where(x => x.NoPartido == id).FirstOrDefault());
        }

        // POST: Partido/Delete/5
        [HttpPost]
        public ActionResult DeleteNoPartido(int id, FormCollection collection)
        {
            try
            {
                Partido partido = DefaultConnection.miAVLNoPartidos.EnOrden().Where(x => x.NoPartido == id).FirstOrDefault();
                DefaultConnection.miAVLNoPartidos.logWriterAsignacion(HomeController.ruta, true);
                string log = "SE ELIMINÓ UN PARTIDO NÚMERO: " + partido.NoPartido.ToString();
                logWriter(log, HomeController.ruta, true);
                DefaultConnection.miAVLNoPartidos.Eliminar(partido);
                return RedirectToAction("IndexNoPartido");
            }
            catch
            {
                return View();
            }
        }

        // GET: Partido/Delete/5
        public ActionResult DeleteFechas(int id)
        {
            logWriter("VISITO ELIMINAR", HomeController.ruta, true);

            return View(DefaultConnection.miAVLFechas.EnOrden().Where(x => x.NoPartido == id).FirstOrDefault());
        }

        // POST: Partido/Delete/5
        [HttpPost]
        public ActionResult DeleteFechas(int id, FormCollection collection)
        {
            try
            {
                Partido partido = DefaultConnection.miAVLFechas.EnOrden().Where(x => x.NoPartido == id).FirstOrDefault();
                DefaultConnection.miAVLFechas.logWriterAsignacion(HomeController.ruta, true);
                string log = "SE ELIMINÓ UN PARTIDO CON FECHA: " + partido.FechaPartido.Day.ToString() + "/" + partido.FechaPartido.Month.ToString() + "/" + partido.FechaPartido.Year.ToString();
                logWriter(log, HomeController.ruta, true);
                DefaultConnection.miAVLFechas.Eliminar(partido);

                return RedirectToAction("IndexFecha");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult BusquedaFecha()
        {
            logWriter("VISITO BUSQUEDA POR FECHA", HomeController.ruta, true);

            return View(DefaultConnection.miBusquedaFecha.ToList());
        }

        public ActionResult BusquedaNoPartido()
        {
            logWriter("VISITO BUSQUEDA NUMERO DE PARTIDO", HomeController.ruta, true);

            return View(DefaultConnection.miBusquedaNoPartidos.ToList());
        }

        [HttpPost]
        public ActionResult BusquedaFecha(string date)
        {
            try
            {
                logWriter("VISITO BUSQUEDA POR FECHA", HomeController.ruta, true);

                Partido partidoBuscadoFecha = DefaultConnection.miAVLFechas.EnOrden().Find(x => x.FechaPartido == DateTime.Parse(date));

                if (partidoBuscadoFecha == null)
                {
                    return HttpNotFound();
                }

                DefaultConnection.miBusquedaFecha.Add(partidoBuscadoFecha);

                return RedirectToAction("BusquedaFecha");
            }
            catch
            {
                return View("BusquedaFecha");
            }
        }

        [HttpPost]
        public ActionResult BusquedaNoPartido(string NoPartido)
        {
            try
            {
                logWriter("VISITO BUSQUEDA NUMERO DE PARTIDO", HomeController.ruta, true);

                Partido partidoBuscadoNoPartido = DefaultConnection.miAVLNoPartidos.EnOrden().Find(x => x.NoPartido == int.Parse(NoPartido));
                if (partidoBuscadoNoPartido == null)

                {

                    return HttpNotFound();

                }
                DefaultConnection.miBusquedaNoPartidos.Add(partidoBuscadoNoPartido);
                return RedirectToAction("BusquedaNoPartido");
            }
            catch
            {
                return View("BusquedaNoPartido");
            }
        }

        public void logWriter(string contenido, string rutaArchivo, bool sobrescribir = true)
        {
            StreamWriter logReporter = new StreamWriter(rutaArchivo, sobrescribir);
            logReporter.WriteLine(contenido + "; " + DateTime.Now);
            logReporter.Close();
        }


    }
}

EDLaboratorio3/Views/Partido/BusquedaFecha.cshtml
@model IEnumerable<EDLaboratorio3.Models.Partido>

@{
    ViewBag.Title = "BusquedaFecha";
}

<h2>BusquedaFecha</h2>

<p>
    @using (Html.BeginForm("BusquedaFecha", "Partido", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <input type="datetime" name="date" />
        <input type="submit" value="Buscar por fecha" />

    }
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NoPartido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaPartido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Grupo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pais1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pais2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estadio)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NoPartido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaPartido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Grupo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pais1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pais2)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estadio)
        </td>
        <td>
        </td>
    </tr>
}

</table>

EDLaboratorio3/Views/Partido/BusquedaNoPartido.cshtml
@model IEnumerable<EDLaboratorio3.Models.Partido>

@{
    ViewBag.Title = "BusquedaNoPartido";
}

<h2>BusquedaNoPartido</h2>

<p>
    @using (Html.BeginForm("BusquedaNoPartido", "Partido", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <input type="text" name="NoPartido" />
        <input type="submit" value="Buscar por numero de partido"/>

    }


</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NoPartido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaPartido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Grupo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pais1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pais2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estadio)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NoPartido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaPartido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Grupo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pais1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pais2)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estadio)
        </td>
    </tr>
}

</table>

EDLaboratorio3/Views/Partido/CreateFecha.cshtml
@model EDLaboratorio3.Models.Partido

@{
    ViewBag.Title = "CreateFecha";
}

<h2>CreateFecha</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Partido</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NoPartido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoPartido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoPartido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaPartido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaPartido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaPartido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Grupo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Grupo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Grupo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pais1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pais1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pais1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pais2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pais2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pais2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estadio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estadio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estadio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "IndexFecha")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EDLaboratorio3/Views/Partido/CreateNoPartido.cshtml
@model EDLaboratorio3.Models.Partido

@{
    ViewBag.Title = "CreateNoPartido";
}

<h2>CreateNoPartido</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Partido</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NoPartido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoPartido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoPartido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaPartido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaPartido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaPartido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Grupo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Grupo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Grupo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pais1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pais1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pais1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pais2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pais2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pais2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estadio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estadio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estadio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "IndexNoPartido")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EDLaboratorio3/Views/Partido/DeleteFechas.cshtml
@model EDLaboratorio3.Models.Partido

@{
    ViewBag.Title = "DeleteFechas";
}

<h2>DeleteFechas</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Partido</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NoPartido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoPartido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaPartido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaPartido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grupo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grupo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pais1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pais1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pais2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pais2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estadio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estadio)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EDLaboratorio3/Views/Partido/DeleteNoPartido.cshtml
@model EDLaboratorio3.Models.Partido

@{
    ViewBag.Title = "DeleteNoPartido";
}

<h2>DeleteNoPartido</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Partido</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NoPartido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoPartido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaPartido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaPartido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grupo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grupo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pais1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pais1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pais2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pais2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estadio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estadio)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EDLaboratorio3/Views/Partido/IndexFecha.cshtml
@model IEnumerable<EDLaboratorio3.Models.Partido>
@{
    ViewBag.Title = "IndexFecha";
}

<h2>IndexFecha</h2>



@using (Html.BeginForm("IndexFecha", "Partido", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
}
<p>
    @Html.ActionLink("Create New", "CreateFecha")
    <input type="button" value="BUSCAR POR FECHA" onclick="location.href='@Url.Action("BusquedaFecha", "Partido" )'" />
    
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NoPartido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaPartido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Grupo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pais1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pais2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estadio)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NoPartido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaPartido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Grupo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pais1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pais2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estadio)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.NoPartido }) |
                @Html.ActionLink("Delete", "DeleteFechas", new { id = item.NoPartido })
            </td>
        </tr>
    }

</table>

EDLaboratorio3/Views/Partido/IndexNoPartido.cshtml
@model IEnumerable<EDLaboratorio3.Models.Partido>
@{
    ViewBag.Title = "IndexNoPartido";
}

<h2>IndexNoPartido</h2>

@using (Html.BeginForm("IndexNoPartido", "Partido", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
}
<p>
    @Html.ActionLink("Create New", "CreateNoPartido")
    <input type="button" value="BUSCAR POR NUMERO DE PARTIDO" onclick="location.href='@Url.Action("BusquedaNoPartido", "Partido" )'" />
    
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NoPartido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaPartido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Grupo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pais1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pais2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estadio)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NoPartido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaPartido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Grupo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pais1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pais2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estadio)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.NoPartido }) |
                @Html.ActionLink("Delete", "DeleteNoPartido", new { id = item.NoPartido })
            </td>
        </tr>
    }

</table>